name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        # Use shell command to find and enter the directory dynamically
        run: |
          cd wtecc-CICD_PracticeCode
          npm install
        
      - name: Run build
        run: |
          cd wtecc-CICD_PracticeCode
          npm run build