name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Reveal structure
        run: |
          echo "Listing all files in the root:"
          find . -maxdepth 2 -not -path '*/.*'
