name: CI workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
