name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and Build
        # This navigates into the nested service folder relative to the workspace root
        working-directory: ./wtecc-CICD_PracticeCode/service
        run: |
          npm install
          npm run build
